-- Flood Alert schema
-- Paste into Supabase SQL editor and run.

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  email text,
  approved boolean not null default false,
  role text not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.device_state (
  device_id text primary key,
  water_level int4,
  updated_at timestamptz not null default now()
);

create table if not exists public.sensor_logs (
  id bigint generated by default as identity primary key,
  device_id text not null,
  water_level int4 not null,
  created_at timestamptz not null default now()
);

create unique index if not exists user_profiles_username_lower_unique_idx on public.user_profiles (lower(username)) where username <> '';
create unique index if not exists user_profiles_email_lower_unique_idx on public.user_profiles (lower(email)) where email <> '';
create index if not exists sensor_logs_device_id_idx on public.sensor_logs (device_id);
create index if not exists sensor_logs_created_at_idx on public.sensor_logs (created_at desc);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

create trigger device_state_set_updated_at
before update on public.device_state
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.user_profiles (id, email, username)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'username', ''))
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.user_profiles enable row level security;
alter table public.device_state enable row level security;
alter table public.sensor_logs enable row level security;

-- Profiles: users can read/update own, admins can read/update all
create policy "profiles_select_self"
  on public.user_profiles for select
  using (auth.uid() = id);

create policy "profiles_update_self"
  on public.user_profiles for update
  using (auth.uid() = id);

create policy "profiles_admin_all"
  on public.user_profiles for all
  using (exists (
    select 1 from public.user_profiles p
    where p.id = auth.uid() and p.role = 'admin'
  ));

-- Device state: approved users and admins can read
create policy "device_state_select_approved"
  on public.device_state for select
  using (exists (
    select 1 from public.user_profiles p
    where p.id = auth.uid() and (p.role = 'admin' or p.approved)
  ));

-- Sensor logs: approved users and admins can read
create policy "sensor_logs_select_approved"
  on public.sensor_logs for select
  using (exists (
    select 1 from public.user_profiles p
    where p.id = auth.uid() and (p.role = 'admin' or p.approved)
  ));
create or replace function public.get_email_by_username(_username text)
returns text as $$
declare
  _email text;
begin
  select email into _email
  from public.user_profiles
  where lower(username) = lower(_username)
  limit 1;
  return _email;
end;
$$ language plpgsql security definer;

grant execute on function public.get_email_by_username(text) to anon;